name: projets

services:
  mysql:
    build: ./mysql
    image: noussa177/projets-mysql:latest
    container_name: projets-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - projets-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: projets-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - projets-net

  frontend:
    build: ./frontend
    container_name: projets-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - projets-net

volumes:
  mysql-data:

networks:
  projets-net:
